title: Mazafard
subtitle: Software Developer
description: >-
  I'm a developer
url: ''
baseurl: ''
urls:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Blog
    url: /blog
  - text: Gallery
    url: /gallery
  - text: Shop
    url: /shop
  - text: Contact
    url: /contact
author_logo: profile.png
author: Maza Fard
author_bio: 'My name is Mohammadreza Asadollahifard.'
author_email: mazafard@gmail.com
author_location: Iran
author_website_url: 'https://mazafard.ir'
typewrite-text: >-
  I'm Developer
author_work_experiences:
  - company_name: -----
    company_logo: jobja.png
    company_url: ''
    designation: Software Engineer
    description: Worked on various Products
    visibility: true
  - company_name: Irantalent
    company_logo: irantalent.png
    company_url: 'https://irantalent.com'
    designation: Software Developer
    description: Worked on various Products
    visibility: true
author_education_details:
  - college_logo: mit.png
    college_name: MIT
    college_url: 'https://mit.org'
    college_degree: CS Engineer
    description: Bachelor of Technology
    visibility: false
author_project_details:
  - project_thumbnail: tao.jpg
    project_title: TAO
    project_description: A Website built for Architecture Project
    project_url: 'https://transformativearchitectureoffice.com/'
    visibility: true
  - project_thumbnail: ibex.jpg
    project_title: Ibex
    project_description: A Platform built for Sellers
    project_url: 'https://ibex.am'
    visibility: true
twitter_username: mazafard
github_username: mazafard
facebook_username: mazafard
linkedin_username: mazafard
behance_username: mazafard
instagram_username: mazafard
medium_username: mazafard
telegram_username: mazafard
dribbble_username: mazafard
flickr_username: mazafard
hyvor_talk_website_id: 476
wakatime_username: mazafard
mailchimp_form_url: >-
  https://
formspree_email: f/myybakjn
markdown: kramdown
highlighter: rouge
permalink: pretty
show_author_work_experiences: true
show_author_education_details: False
show_author_project_details: true
paginate: 4
per_page: 4
paginate_path: '/blog/page/:num/'
collections:
  products:
    output: true
  authors:
    output: true
defaults:
  - scope:
      path: gallery
    values:
      permalink: '/:path/:basename:output_ext'
  - scope:
      path: ''
      type: authors
    values:
      layout: author
      permalink: '/blog/authors/:slug'
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
destination: ./build
